# frozen_string_literal: true

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

# [START fleetengine_v1_generated_VehicleService_GetVehicle_sync]
require "maps/fleetengine/v1"

##
# Snippet for the get_vehicle call in the VehicleService service
#
# This is an auto-generated example demonstrating basic usage of
# Maps::Fleetengine::V1::VehicleService::Client#get_vehicle. It may require
# modification in order to execute successfully.
#
def get_vehicle
  # Create a client object. The client can be reused for multiple calls.
  client = Maps::Fleetengine::V1::VehicleService::Client.new

  # Create a request. To set request fields, pass in keyword arguments.
  request = Maps::Fleetengine::V1::GetVehicleRequest.new

  # Call the get_vehicle method.
  result = client.get_vehicle request

  # The returned object is of type Maps::Fleetengine::V1::Vehicle.
  p result
end
# [END fleetengine_v1_generated_VehicleService_GetVehicle_sync]
